namespace StudyLab.Migrations
{
    using System.Data.Entity.Migrations;

    public partial class Questions : DbMigration
    {
        public override void Up()
        {
            Sql(@"SET IDENTITY_INSERT [dbo].[Questions] ON
INSERT INTO [dbo].[Questions] ([Id], [QuestionText], [AnswerText], [TypeId]) VALUES (1, N'What is JavaScript?', N'JavaScript is a high-level, dynamic, weakly typed, prototype-based, multi-paradigm, and interpreted programming language', 1)
INSERT INTO [dbo].[Questions] ([Id], [QuestionText], [AnswerText], [TypeId]) VALUES (2, N'What is ReactJS?', N'A JavaScript library for building user interfaces.', 3)
INSERT INTO [dbo].[Questions] ([Id], [QuestionText], [AnswerText], [TypeId]) VALUES (3, N'What is WebAPI?', N'ASP.NET Web API is a framework that simplifies building HTTP services for broader range of clients (including browsers as well as mobile devices) on top of .NET Framework.', 4)
INSERT INTO [dbo].[Questions] ([Id], [QuestionText], [AnswerText], [TypeId]) VALUES (4, N'What is MVC?', N'The Model-View-Controller (MVC) architectural design pattern separates an application into three main components: the model, the view, and the controller. The ASP.NET MVC framework provides an alternative to the ASP.NET Web Forms pattern for creating Web applications. The ASP.NET MVC framework is a lightweight, highly testable presentation framework.', 2)
INSERT INTO [dbo].[Questions] ([Id], [QuestionText], [AnswerText], [TypeId]) VALUES (55, N'What is convention based routing?', N'Convention Routing approaches the routing problem general-case-first; by default, you are given a route that will probably match most if not all of your routes, and are asked to define if there are any more specific routes you would also like to handle.', 2)
INSERT INTO [dbo].[Questions] ([Id], [QuestionText], [AnswerText], [TypeId]) VALUES (56, N'What is convention based routing?', N'Convention Routing approaches the routing problem general-case-first; by default, you are given a route that will probably match most if not all of your routes, and are asked to define if there are any more specific routes you would also like to handle.', 2)
INSERT INTO [dbo].[Questions] ([Id], [QuestionText], [AnswerText], [TypeId]) VALUES (57, N'What is Attribute based routing?', N'Attribute Routing (introduced in MVC 5) is the ability to add routes to the Route Table via attributes so that the route definitions are in close proximity to their corresponding actions.', 2)
INSERT INTO [dbo].[Questions] ([Id], [QuestionText], [AnswerText], [TypeId]) VALUES (58, N'What is Dependency Injection?', N'Dependency injection is basically providing the objects that an object needs (its dependencies) instead of having it construct them itself.', 2)
INSERT INTO [dbo].[Questions] ([Id], [QuestionText], [AnswerText], [TypeId]) VALUES (59, N'What are the benefits of Dependency Injection?', N'It makes it simple to manage dependencies between objects, that in turn, makes it easier to break coherent functionality off into it''s own contract (Interface). Unit testing is much more simple. Maintains loosely coupled code and re-usability.', 2)
INSERT INTO [dbo].[Questions] ([Id], [QuestionText], [AnswerText], [TypeId]) VALUES (60, N'What is a Database Context?', N'A session with the database used for applying changes or creating data.', 2)
INSERT INTO [dbo].[Questions] ([Id], [QuestionText], [AnswerText], [TypeId]) VALUES (61, N'What is the significance of, and reason for, wrapping the entire content of a JavaScript source file in a function block?', N'This is an increasingly common practice, employed by many popular JavaScript libraries (jQuery, Node.js, etc.). This technique creates a closure around the entire contents of the file which, perhaps most importantly, creates a private namespace and thereby helps avoid potential name clashes between different JavaScript modules and libraries.', 1)
INSERT INTO [dbo].[Questions] ([Id], [QuestionText], [AnswerText], [TypeId]) VALUES (62, N'What is a “closure” in JavaScript?', N'A closure is an inner function that has access to the variables in the outer (enclosing) function’s scope chain.', 1)
INSERT INTO [dbo].[Questions] ([Id], [QuestionText], [AnswerText], [TypeId]) VALUES (63, N'Can you name two programming paradigms important for JavaScript app developers?', N'JavaScript is a multi-paradigm language, supporting imperative/procedural programming along with OOP (Object-Oriented Programming) and functional programming. JavaScript supports OOP with prototypal inheritance.', 1)
INSERT INTO [dbo].[Questions] ([Id], [QuestionText], [AnswerText], [TypeId]) VALUES (64, N'What is functional programming?', N'Functional programming produces programs by composing mathematical functions and avoids shared state & mutable data.', 1)
INSERT INTO [dbo].[Questions] ([Id], [QuestionText], [AnswerText], [TypeId]) VALUES (65, N'Name 3 functional programming languages?', N'Lisp, ML, Haskell, Erlang, Clojure, Elm, F Sharp, OCaml.', 1)
INSERT INTO [dbo].[Questions] ([Id], [QuestionText], [AnswerText], [TypeId]) VALUES (66, N'When is classical inheritance an appropriate choice?', N'The answer is never, or almost never. Certainly never more than one level. Multi-level class hierarchies are an anti-pattern.', 1)
INSERT INTO [dbo].[Questions] ([Id], [QuestionText], [AnswerText], [TypeId]) VALUES (67, N'Name 3 functional programming languages?', N'Lisp, ML, Haskell, Erlang, Clojure, Elm, F Sharp, OCaml.', 1)
INSERT INTO [dbo].[Questions] ([Id], [QuestionText], [AnswerText], [TypeId]) VALUES (68, N'What are the Advantages of Using ASP.NET Web API?', N'It works the HTTP way using standard HTTP verbs like GET, POST, PUT, DELETE, etc. for all CRUD operations. Complete support for routing. Supports Model binding and Validation. Response generated in JSON or XML format.', 4)
INSERT INTO [dbo].[Questions] ([Id], [QuestionText], [AnswerText], [TypeId]) VALUES (69, N'What New Features are Introduced in ASP.NET Web API 2.0?', N'Attribute Routing - External Authentication - CORS (Cross-Origin Resource Sharing) - OWIN (Open Web Interface for .NET) Self Hosting - IHttpActionResult - Web API OData', 4)
INSERT INTO [dbo].[Questions] ([Id], [QuestionText], [AnswerText], [TypeId]) VALUES (70, N'WCF Vs ASP.NET Web API?', N'Windows Communication Foundation is designed to exchange standard SOAP-based messages using variety of transport protocols like HTTP, TCP, NamedPipes or MSMQ, etc. On the other hand, ASP.NET API is a framework for building non-SOAP based services over HTTP only.', 4)
INSERT INTO [dbo].[Questions] ([Id], [QuestionText], [AnswerText], [TypeId]) VALUES (71, N'MVC Vs ASP.NET Web API?', N'Web API framework is to generate HTTP services that reach more clients by generating data in raw format, for example, plain XML or JSON string. So, ASP.NET Web API creates simple HTTP services that renders raw data. On the other hand, ASP.NET MVC framework is used to develop web applications that generates Views as well as data. ASP.NET MVC facilitates in rendering HTML easy.', 4)
INSERT INTO [dbo].[Questions] ([Id], [QuestionText], [AnswerText], [TypeId]) VALUES (72, N'How to Return View from ASP.NET Web API Method?', N'No, we can''t return view from ASP.NET Web API method.', 4)
INSERT INTO [dbo].[Questions] ([Id], [QuestionText], [AnswerText], [TypeId]) VALUES (73, N'How to Restrict Access to Web API Method to Specific HTTP Verb?', N'Attribute programming plays its role here. We can easily restrict access to an ASP.NET Web API method to be called using a specific HTTP method.', 4)
INSERT INTO [dbo].[Questions] ([Id], [QuestionText], [AnswerText], [TypeId]) VALUES (74, N'Can we use Web API with ASP.NET Web Form?', N'Yes, ASP.NET Web API is bundled with ASP.NET MVC framework but still it can be used with ASP.NET Web Form.', 4)
INSERT INTO [dbo].[Questions] ([Id], [QuestionText], [AnswerText], [TypeId]) VALUES (75, N'What does URL, URI and URN stand for?', N'Universal Resource Locator - Universal Resource Identifier - Universal Resource Name.', 4)
INSERT INTO [dbo].[Questions] ([Id], [QuestionText], [AnswerText], [TypeId]) VALUES (76, N'Name all of the HTTP method verbs.', N'GET - HEAD - POST - PUT - DELETE - CONNECT - OPTIONS - TRACE', 4)
INSERT INTO [dbo].[Questions] ([Id], [QuestionText], [AnswerText], [TypeId]) VALUES (77, N'Name all the HTTP Status codes.', N'1xx: Informational-It means the request has been received and the process is continuing. 2xx: Success-It means the action was successfully received, understood, and accepted. 3xx: Redirection-It means further action must be taken in order to complete the request. 4xx: Client Error-It means the request contains incorrect syntax or cannot be fulfilled 5xx: Server Error-It means the server failed to fulfill an apparently valid request.', 4)
INSERT INTO [dbo].[Questions] ([Id], [QuestionText], [AnswerText], [TypeId]) VALUES (78, N'What is REST?', N'REST (Representational State Transfer) is an architectural style and a set of principles for designing applications and it dictates to use HTTP for making calls for communications instead of complex mechanism like CORBA, RPC or SOAP.', 4)
INSERT INTO [dbo].[Questions] ([Id], [QuestionText], [AnswerText], [TypeId]) VALUES (79, N'Explain briefly CORS(Cross-Origin Resource Sharing)?', N'CORS (Cross-origin resource sharing) is a technique that allows restricted resources on a web page to be requested from another domain outside the domain of which the first resource was served.', 4)
INSERT INTO [dbo].[Questions] ([Id], [QuestionText], [AnswerText], [TypeId]) VALUES (80, N'Explain briefly OWIN (Open Web Interface for .NET) Self Hosting?', N'OWIN (Open Web Interface for .NET) is an interface for .NET between .NET web applications and web server. It is an open source technology. OWIN aims to decouple the connection between ASP.NET applications and IIS by giving a standard interface.', 4)
INSERT INTO [dbo].[Questions] ([Id], [QuestionText], [AnswerText], [TypeId]) VALUES (81, N'What is ASP.NET Web API OData?', N'The Open Data Protocol (OData) is a data access protocol created for the web. OData gives a consistent procedure to query and manipulates data sets via CRUD operations (Create, Retrieve, Update, and Delete). ASP.NET web API supports each of the v3 and v4 protocol.', 4)
SET IDENTITY_INSERT [dbo].[Questions] OFF
");
        }

        public override void Down()
        {
        }
    }
}
